version: "2"

linters:
  default: standard
  enable:
    - misspell
    - revive
    - gosec
    - gocritic
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - wastedassign
  settings:
    revive:
      rules:
        - name: exported
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
          - gocritic

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
