version: 2

project_name: monero-exporter

builds:
  - id: monero-exporter
    main: ./cmd/monero-exporter
    env:
      - CGO_ENABLED=0
    binary: monero-exporter
    ldflags:
      - -w -s -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers_v2:
  - ids:
      - monero-exporter
    dockerfile: Dockerfile
    images:
      - "ghcr.io/rossigee/monero-exporter"
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64/v8
    sbom: false
